class _BotCommands:
    def __init__(self):
        self.StartCommand = 'stkrkrjrjrje'
        self.MirrorCommand = 'mirrorT'
        self.UnzipMirrorCommand = 'unzipmirrorT'
        self.TarMirrorCommand = 'tarmirrorT'
        self.CancelMirror = 'cancelT'
        self.CancelAllCommand = 'cancelallT'
        self.ListCommand = 'listT'
        self.StatusCommand = 'statusT'
        self.AuthorizedUsersCommand = 'usersT'
        self.AuthorizeCommand = 'authorizeT'
        self.UnAuthorizeCommand = 'unauthorizeT'
        self.AddSudoCommand = 'addsudoT'
        self.RmSudoCommand = 'rmsudoT'
        self.PingCommand = 'pingT'
        self.RestartCommand = 'restartT'
        self.StatsCommand = 'statsT'
        self.HelpCommand = 'helpT'
        self.LogCommand = 'logT'
        self.SpeedCommand = 'speedtestT'
        self.CloneCommand = 'cloneT'
        self.WatchCommand = 'watchT'
        self.TarWatchCommand = 'tarwatchgs'
        self.DeleteCommand = 'delT'
        self.UsageCommand = 'usageT'

BotCommands = _BotCommands()
