class _BotCommands:
    def __init__(self):
        self.StartCommand = 'stkrkrjrjrje'
        self.MirrorCommand = 'mirrortr'
        self.UnzipMirrorCommand = 'unzipmirrortr'
        self.TarMirrorCommand = 'tarmirrortr'
        self.CancelMirror = 'canceltr'
        self.CancelAllCommand = 'cancelalltr'
        self.ListCommand = 'listtr'
        self.StatusCommand = 'statustr'
        self.AuthorizedUsersCommand = 'userstr'
        self.AuthorizeCommand = 'authorizetr'
        self.UnAuthorizeCommand = 'unauthorizetr'
        self.AddSudoCommand = 'addsudotr'
        self.RmSudoCommand = 'rmsudotr'
        self.PingCommand = 'pingtr'
        self.RestartCommand = 'restartr'
        self.StatsCommand = 'statstr'
        self.HelpCommand = 'helptr'
        self.LogCommand = 'logtr'
        self.SpeedCommand = 'speedtestr'
        self.CloneCommand = 'clonetr'
        self.WatchCommand = 'watchtr'
        self.TarWatchCommand = 'tarwatchtr'
        self.DeleteCommand = 'deltr'
        self.UsageCommand = 'usagetr'

BotCommands = _BotCommands()
