class _BotCommands:
    def __init__(self):
        self.StartCommand = 'stkrkrjrjrje'
        self.MirrorCommand = 'mirrorgs'
        self.UnzipMirrorCommand = 'unzipmirrorgs'
        self.TarMirrorCommand = 'tarmirrorgs'
        self.CancelMirror = 'cancelgs'
        self.CancelAllCommand = 'cancelallgs'
        self.ListCommand = 'listgs'
        self.StatusCommand = 'statusgs'
        self.AuthorizedUsersCommand = 'usersgs'
        self.AuthorizeCommand = 'authorizegs'
        self.UnAuthorizeCommand = 'unauthorizegs'
        self.AddSudoCommand = 'addsudogs'
        self.RmSudoCommand = 'rmsudogs'
        self.PingCommand = 'pinggs'
        self.RestartCommand = 'restartgs'
        self.StatsCommand = 'statsgs'
        self.HelpCommand = 'helpgs'
        self.LogCommand = 'loggs'
        self.SpeedCommand = 'speedtestgs'
        self.CloneCommand = 'clonegs'
        self.WatchCommand = 'watchgs'
        self.TarWatchCommand = 'tarwatchgs'
        self.DeleteCommand = 'delgs'
        self.UsageCommand = 'usagegs'

BotCommands = _BotCommands()
